services:
  - type: web
    name: centrale-potins-maps
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
